import type { Metadata } from 'next';
import './globals.css';
import { Provider } from '../components/ui/provider';
import { Flex } from '@chakra-ui/react';
import { Topbar } from '../components/Topbar';
import { Footer } from '../components/Footer';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// app/layout.tsx
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Flex direction="column" minH="100vh">
            <Topbar />
            {/* Usuwamy p={8} i bg, pozwalamy children wypełnić przestrzeń */}
            <Flex as="main" direction="column" flex={1}>
              {children}
            </Flex>
            <Footer />
          </Flex>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
