"""Add ticker

Revision ID: 3465c23de79a
Revises: b271884d8b01
Create Date: 2026-01-09 21:52:44.599284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3465c23de79a'
down_revision: Union[str, Sequence[str], None] = 'b271884d8b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_name', sa.Enum('EUROPE', 'POLAND', name='tickerregion'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickers')
    # ### end Alembic commands ###
