"""Initial migration

Revision ID: b271884d8b01
Revises: 
Create Date: 2026-01-08 10:20:53.012483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b271884d8b01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('STOCK', 'CRYPTO', 'OTHER', name='financingtype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('classifier', sa.Enum('STOCK', 'CRYPTO', name='classifier'), nullable=True),
    sa.Column('dataset_ticker', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_models')
    # ### end Alembic commands ###
